---
- hosts: localhost
  connection: local

  tasks:
  - name: Brew install or update preinstalled
    homebrew:
      name: "{{ item }}"
      state: present
    with_items:
      - awscli
      - bitwarden-cli
      - docker
      - git
      - thefuck
      - elinks
      - ettercap
      - htop
      - nmap
      - speedtest-cli
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions

  - name: Brew cask install applications
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - google-chrome
      - brave
      - franz
      - spotify
      - intellij-idea
      - firefox
      - iterm2
      - visual-studio-code
      - charles
      - sourcetree
      - spotify

  - name: Install oh my zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

  - name: Install SDK Development Kit Manager
    shell: curl -s "https://get.sdkman.io" | bash sleep 50 "$HOME/.sdkman/bin/sdkman-init.sh"

  - name: Copy configured zshrc
    copy:
      src: ./zshrc
      dest: ~/.zshrc

  - name: Create projects directory
    file:
      path: ~/projects
      state: directory

  - name: Create tmp directory
    file:
      path: ~/tmp
      state: directory